name: DevelopCI
on:
  push:
    branches: [ add-ci ]
  pull_request:
    branches: [ add-ci ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: google-task-creator
        path: |
          .
          !*.md
          !.git*
