name: DevelopCI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Zip folder to SNAPSHOT
      run: zip -r google-task-creator-SNAPSHOT.zip . -x ".git/*" ".github/*"
    - name: Finish
      run: echo "finished"
      